server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html/portal;
    index index.html;

    location /admin/ {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

    location /downloads/ {
        alias /usr/share/nginx/html/downloads/;
        autoindex off;
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
