services:
  vaultsync-be:
    image: ligson/vaultsync-be:latest
    container_name: vaultsync-be
    restart: always
    ports:
      - "127.0.0.1:18080:8080"
    command: ["-config", "/app/config.yaml"]
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/data
